#!/usr/bin/env python3

XWIN_SIZE=1
YWIN_SIZE=1
BUFFER_SIZE=3000

xdata, ydata = [], [] 

def get_inp():
    import fileinput
    for line in fileinput.input():
        _ = str(line).split()
        if len(_) != 2: 
            continue #Very lenient input checking
        try:
            x=float(_[0])
            y=float(_[1])
        except ValueError:
            continue
        xdata.append(x)
        ydata.append(y)
        if(len(xdata) == BUFFER_SIZE):
            del xdata[0]
            del ydata[0]

def plot():
    import matplotlib.pyplot as plt 
    import matplotlib.animation as animation 
    plt.style.use('dark_background')

    fig = plt.figure() 


    ax = plt.axes(xlim=(0, 10), ylim=(-1,1)) 
    line, = ax.plot([], [], lw=2) 

    def animate(_): 
        line.set_data(xdata, ydata) 
        return line, 

    plt.title('Real-time plot') 

    _= animation.FuncAnimation(fig, animate,blit=True,interval=20)

    plt.show()

def main():
    import threading
    inp_thread = threading.Thread(target=get_inp)
    inp_thread.start()
    plot()

if __name__ == '__main__':
    main()
